spring:
  data:
  elasticsearch:
    rest:
      uris: ["192.168.44.132:9200"]
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.44.132:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
      properties:
        path:
          logs: ./elasticsearch/log #elasticsearch日志存储目录
          data: ./elasticsearch/data #elasticsearch数据存储目录